spring:
  application:
    name: Qr-Code
  datasource:
    url: jdbc:postgresql://localhost:5432/qrcode_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 9090

qrcode:
  path: ${QRCODE_PATH}